<script>
	import TypeIt from 'typeit';
	import Header from '../components/header.svelte';
	import { onMount } from 'svelte';
	onMount(() => {
		const containerRef = document.getElementById('container');
		new TypeIt('#element', {
			lifeLike: false,
			speed: 0,
			loop: true
		})
			.type('i')
			.pause(623)
			.type("'")
			.pause(337)
			.type('m')
			.pause(350)
			.type(' ')
			.pause(253)
			.type('a')
			.move(-4, { speed: 573 })
			.pause(550)
			.delete(3, { instant: true })
			.pause(400)
			.type('I')
			.move(4, { speed: 415 })
			.type(' ')
			.pause(510)
			.type('D')
			.pause(576)
			.type('e')
			.pause(350)
			.type('v')
			.pause(170)
			.type('e')
			.pause(481)
			.type('l')
			.pause(266)
			.type('o')
			.pause(297)
			.type('p')
			.pause(236)
			.type('e')
			.pause(164)
			.type('r')
			.pause(627)
			.delete(1)
			.pause(284)
			.delete(1)
			.pause(199)
			.delete(1)
			.pause(254)
			.delete(1)
			.pause(223)
			.delete(1)
			.pause(274)
			.delete(1)
			.pause(200)
			.delete(1)
			.pause(253)
			.delete(1)
			.pause(374)
			.delete(1)
			.pause(423)
			.type('P')
			.pause(486)
			.type('r')
			.pause(247)
			.type('o')
			.pause(226)
			.type('g')
			.pause(254)
			.type('r')
			.pause(300)
			.type('a')
			.pause(250)
			.type('m')
			.pause(301)
			.type('m')
			.pause(299)
			.type('e')
			.pause(227)
			.type('r')
			.pause(624)
			.delete(1)
			.pause(626)
			.delete(1)
			.pause(324)
			.delete(1)
			.pause(253)
			.delete(1)
			.pause(260)
			.delete(1)
			.pause(350)
			.delete(1)
			.pause(400)
			.delete(1)
			.pause(363)
			.delete(1)
			.pause(400)
			.delete(1)
			.pause(324)
			.delete(1)
			.pause(507)
			.type('D')
			.pause(472)
			.type('e')
			.pause(396)
			.type('s')
			.pause(377)
			.type('i')
			.pause(297)
			.type('g')
			.pause(300)
			.type('n')
			.pause(326)
			.type('e')
			.pause(337)
			.type('r')
			.pause(627)
			.delete(1)
			.pause(436)
			.delete(1)
			.pause(376)
			.delete(1)
			.pause(291)
			.delete(1)
			.pause(275)
			.delete(1)
			.pause(271)
			.delete(1)
			.pause(303)
			.delete(1)
			.pause(297)
			.delete(1)
			.pause(496)
			.type('P')
			.pause(490)
			.type('r')
			.pause(267)
			.type('o')
			.pause(696)
			.type('b')
			.pause(639)
			.type('l')
			.pause(512)
			.type('e')
			.pause(210)
			.type('m')
			.pause(263)
			.type(' ')
			.pause(450)
			.type('S')
			.pause(500)
			.type('l')
			.pause(361)
			.type('o')
			.pause(326)
			.type('v')
			.pause(300)
			.type('e')
			.pause(340)
			.type('r')
			.pause(611)
			.delete(1)
			.pause(366)
			.delete(1)
			.pause(237)
			.delete(1)
			.pause(273)
			.delete(1)
			.pause(254)
			.delete(1)
			.pause(287)
			.delete(1)
			.pause(223)
			.delete(1)
			.pause(360)
			.delete(1)
			.pause(340)
			.delete(1)
			.pause(373)
			.delete(1)
			.pause(367)
			.delete(1)
			.pause(396)
			.delete(1)
			.pause(300)
			.delete(1)
			.pause(317)
			.delete(1)
			.pause(339)
			.type('D')
			.pause(540)
			.type('e')
			.pause(343)
			.type('s')
			.pause(264)
			.type('i')
			.pause(273)
			.type('g')
			.pause(287)
			.type('n')
			.pause(237)
			.type('e')
			.pause(287)
			.type('r')
			.go();
	});
</script>

<div>
	<div class=" relative min-h-screen">
		<Header />
		<div
			class="absolute inset-0 h-full w-full items-center px-5 py-24 [background:radial-gradient(125%_125%_at_50%_10%,#fff7ed_40%,#fb943c_100%)]"
		>
			<div class="container mx-auto grid sm:grid-cols-none grid-cols-none md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-2 2xl:grid-cols-2 h-full w-full items-center justify-center">
				<div class="mx-auto w-full  flex-col justify-center items-center relative">
					<h1 class="my-8 xl:text-xl text-md font-bold uppercase text-gray-600">👋, My name is Pasindu</h1>
					<!-- svelte-ignore element_invalid_self_closing_tag -->
					<span id="element" class="absolute  2xl:text-7xl xl:text-6xl md:text-5xl sm:text-4xl text-2xl font-extrabold" />
					<h3 class="mt-28 2xl:mt-32 xl:mt-32 md:mt-32 xl:text-xl text-md text-gray-600">Based in Colombo, Sri Lanka</h3>
				</div>
				<div class="mx-auto w-full sm:hidden md:block hidden">
					<img src="/home-draw.png" alt="" />
				</div>
			</div>
		</div>
	</div>
</div>

<!-- strings: ["I'm a Developer", "I'm a Designer", "I'm a Programmer","I'm an Innovator","I'm a Problem Solver."], -->
