import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="description"
          content="Hi, I'm Pasindu Pramodya, a passionate software engineer specializing in web development, backend systems, and scalable solutions. Explore my projects, resume, and contact details here."
        />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" type="image/svg+xml" href="/favicons/favicon.ico" />
        <meta
          name="keywords"
          content="software engineer, fullstack developer, portfolio, backend developer, frontend developer, web development, coding projects, software engineering portfolio, tech blog, freelance software developer, open-source contributor"
        />
        <meta name="author" content="Pasindu Pramodya" />
        <meta property="og:type" content="website" />
        <meta
          property="og:title"
          content="Pasindu Pramodya - Software Engineer Portfolio"
        />
        <meta
          property="og:description"
          content="Discover my portfolio featuring projects, skills, and my resume. Let's collaborate on exciting software development projects!"
        />
        <meta property="og:url" content="https://pasindupramodya.com" />
        <meta
          property="og:image"
          content="https://pasindupramodya.com/profile.jpeg"
        />

        <link rel="canonical" href="https://pasindupramodya.com" />
        <meta name="robots" content="index, follow" />
        <meta property="og:locale" content="en_US" />
        <meta property="og:site_name" content="Pasindu Pramodya Portfolio" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
